### PR TITLE
Reply button translatable * Delete Old editor-style * Enable HTML5 form Input

### PR DESCRIPTION
**Pull request by AdsonCicilioti**
## Hi Eddie!

I follow and use this project already for a while, and now I bring my humble contribution to try to make it even better.

Well, they are:

1. Make the Reply button translatable
2. Remove the old editor-style.css file.
3. New searchform.php file with HTML5 fields and function to enable the HTML5 support in emails and URL fields in the comment form. Optimizing the use of mobile devices keyboard. Replace the submit input by submit button for better styling, enabling the use of the font-icons

### CODE REVIEW

**Comment by AdsonCicilioti** [comment]
I opened the issue #725 and I said a possible solution, but would like to know your view on this.

Thx!

**Comment by eddiemachado** [comment]
Good stuff. I'm going to try and rework that admin css at some point, but if it's not being used, we should just get rid of it.

Thanks!

**Comment by AdsonCicilioti** [comment]
Yep!

**Comment by Hlsgs** [comment]
But why remove the editor-style.css? I've been using that..

**Comment by AdsonCicilioti** [comment]
@Hlsgs, the editor-style.css now have a scss version, is compiled to style.css. This editor-style.css is junk of the bones version outdated.

**Comment by Hlsgs** [comment]
@AdsonCicilioti i see no reference to editor-style.scss in style.scss. Does WP no longer load editor-style.css from the theme's root folder? What's the logic of this?

**Comment by AdsonCicilioti** [comment]
@Hlsgs Excuse Me. I was wrong as the relationship with the build in style.css. In fact it is compiled in its own editor-style.css version and is in the css folder. And it is usually loaded from the new location. What has changed is that he won a SCSS version and the compiled file is in library / css. So removed the obsolete file that was at the root.

**Comment by Hlsgs** [comment]
@AdsonCicilioti Ah, I get it. I was confused because in the master release there is no compiled editor-style.css in library/css. Cool. That's the proper place for it. Now let me modify my gruntfile :)
Btw, if you have a ready compiled version you should make a request to put it in library/css for the people who still don't use preprocessors.

**Comment by AdsonCicilioti** [comment]
Ok @Hlsgs. I Create a pull #752 for fix this issue.

**Pull request merged**
