### PR TITLE
login-logo

### PR DESCRIPTION
**Pull request by andrewbanchich**
Adds [vectorized login logo](https://github.com/andrewbanchich/bones/blob/master/library/images/login-logo.svg) for various device resolutions and updated png version for [extra pirate hat goodness](https://github.com/eddiemachado/bones/pull/851/files).

Any thoughts on using .svg for this instead of .png? I think the different in filesize is pretty small.

### CODE REVIEW

**Comment by Hlsgs** [comment]
Pointless IMHO, since the login logo should be replaced anyway.

**Comment by andrewbanchich** [comment]
@Hlsgs Still, I see no reason to _not_ use higher quality assets in the default theme.

**Comment by Hlsgs** [comment]
Well, a beginner may have trouble creating a replacement SVG and it's much easier for them to just replace/overwrite a PNG of **known dimensions**.
@eddiemachado has always made a point of making Bones as beginner friendly and educational and i suspect this is the reason why he didn't resort to https://placehold.it/ or equvalents, which would have beed the cleanest and most natural path for advanced users.
Also, IE8 compatibility as that is unfortunately sometimes still requested.

**Comment by andrewbanchich** [comment]
@Hlsgs Ah, makes sense! How about just the png version then?

**Comment by Hlsgs** [comment]
I see nothing wrong with that. :)

**Pull request closed without merging**
