### PR TITLE
Adding transform() sass mixin

### PR DESCRIPTION
**Pull request by elron**
I find myself adding this on every single site I'm making with bones...
Will appreciate if you just accept <3

Elron

### CODE REVIEW

**Comment by Hlsgs** [comment]
Dude you seriously need to take a look at autoprefixed. And i mean really :)
https://github.com/nDmitry/grunt-autoprefixer

**Comment by elron** [comment]
Wow. You blowed my mind!
I actually use Prepros for that task, not grunt. but it does the same job! (AutoPrefix CSS)

Thanks for enlightening my eyes :)

**Comment by Hlsgs** [comment]
You're welcome!
While Prepros and equivalents are all fine and dandy in principle, Grunt is very much worth the relatively steep learning curse, as it does so much more for you. Just to give an example, i have it base64 encoding the small images in my project into SASS variables i can use as i please for CSS encodes. Another great example is that i have it adding a real hash to the filename of my production CSS and JS, and, here's the kicker, modifiying bones.php with the versioned filenames. The list goes on an on.
It may take you two weeks until you come up with a serviceable Gruntfile.js, and you will keep perfecting it as you encounter new projects, but you will thank yourself for taking the step away from Prepros and the likes :)

Oh, and did i mention the speed of the node-sass compiler? ;)

**Comment by elron** [comment]
@Hlsgs Thats cool, I might consider it in the future.
For now I'm just really enthusiastic about Prepros that I don't feel the need to change.
Don't fix what's not broken! :) for now its doing all my wishes and more, also I'm still learning it. Maybe when my new toy will turn boring to me, I will try grunt.

By the way, about the small images into base64. If you turn one image into a variable, and repeat it in the course of... I don't know. 10 times? Wouldn't it be better to just load the image one time - as an image, insted of printing the varaiable 10 times in the code? (in terms of speed - it will make the code larger)

**Comment by Hlsgs** [comment]
Doesn't work like that. Grunt creates a file with variable names and the base64 encode and i use the ones i please. SO only the ones i actually need end up in my production css, and only do so once. The best example would be a 1x1 pixel transparent gif that is sometime needed. Having your main CSS a few bytes larger is way better than having an extra http call.
That being said, if the image is used several time on the page, it's matter of writing SASS so as to only declare it once as a background image for several elements. And even if you don't grunt-contrib-cssmin is pretty smart about this.

**Comment by elron** [comment]
Ok. so it works on small base64 images such as 1x1 transparent, as you mentioned. but what if its an icon, or something like that? just from curiacity, is it possible for grunt to find an svg file that is imported in the SCSS file and convert it to base64 to save up extra http call?
I'm talking here about custom base64 images. not ones you use like 1x1 transparent.

**Comment by Hlsgs** [comment]
Yes. It's possible for all resources. I even have it encoding custom font packs from Icomoon if I'm only using a few glyphs and i consider saving a hhtp call meritory compared to the added size of the production css. the possibilities are praclically limitless with Grunt(or Gulp for that matter).
Base64, prefixing, image minification, CSS sprites, a custom modernizr according to the feature you are using, livereload, backups, even serialized search-replace and export you DB for moving to the production server etc.
Whatever you can imagine, theres an NPM module for that.
If you get into it, you'll have a hard time believing you didn't to it sooner. I sure did.

**Comment by elron** [comment]
OKAY! so its been a few month since we talked here, meanwhile I did try grunt for several times, and yes, you are completely right!!!!! Grunt is very cool. So thank you again.

I wonder, if you're using bones & grunt, do you have your own grunt.js for bones?

**Comment by Hlsgs** [comment]
I do, but it's highly customized to my work style. I wouldn't be doing you a favor by providing it as it's been evolving for some years and you would probably have a hard time understanding it. When I first got into grunt I tried different configs, then quickly realized that the best course of action is rolling your own from scratch.
I will, however, show you my list of package.json dependencies, so you don't have to go through the process of testing until you find the best modules these days:
```
    "grunt": "latest",
    "grunt-base64": "latest",
    "grunt-cache-bust": "latest",
    "grunt-concurrent": "latest",
    "grunt-contrib-clean": "latest",
    "grunt-contrib-concat": "latest",
    "grunt-contrib-imagemin": "latest",
    "grunt-contrib-uglify": "latest",
    "grunt-contrib-watch": "latest",
    "grunt-datauri": "latest",
    "grunt-modernizr": "latest",
    "grunt-newer": "latest",
    "grunt-postcss": "latest",
    "grunt-sass": "latest",
    "grunt-string-replace": "latest",
    "jit-grunt": "latest",
```

**Pull request closed without merging**
